# Generated by Django 6.0 on 2025-12-31 13:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('biographie', models.TextField(blank=True, null=True, verbose_name='Biographie')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='instructors/photos/', verbose_name='Photo de profil')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
            ],
            options={
                'verbose_name': 'Instructeur',
                'verbose_name_plural': 'Instructeurs',
                'ordering': ['nom_complet'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publié', 'Publié'), ('archivé', 'Archivé')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('instructeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.instructor', verbose_name='Instructeur')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('date_completion', models.DateTimeField(blank=True, null=True, verbose_name='Date de complétion')),
                ('note_finale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Note finale')),
                ('statut', models.CharField(choices=[('en cours', 'En cours'), ('complété', 'Complété'), ('abandonné', 'Abandonné')], default='en cours', max_length=10, verbose_name='Statut')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='projet.course', verbose_name='Cours')),
                ('étudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_inscription'],
                'unique_together': {('cours', 'étudiant')},
            },
        ),
    ]
