# Generated by Django 6.0 on 2025-12-31 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0002_studentprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['titre'], 'permissions': [('can_publish_course', 'Peut publier un cours'), ('can_view_statistics', 'Peut voir les statistiques')], 'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
    ]
